--oef1

INSERT INTO departments
(department_id,department_name)
VALUES(15,'Human Resources');

INSERT INTO locations
(department_id, location)
VALUES(15,'Antwerpen');

INSERT INTO employees
(employee_id,first_name,last_name,department_id)
VALUES ('999999999','Jan','Janssens',15);

INSERT INTO projects
(project_id, project_name, location, department_id)
VALUES(40,'Opleidingen','Antwerpen',15);

UPDATE employees
SET manager_id  = '999999999',department_id = 15
WHERE employee_id = '999333333';

UPDATE employees
SET manager_id = '999333333',department_id = 15
WHERE employee_id = '999111111';

INSERT INTO tasks
(employee_id, project_id, hours)
VALUES('999333333',40,20);

INSERT INTO tasks
(employee_id, project_id, hours)
VALUES('999111111',40,10);

select * from employees;


--oef3
ALTER TABLE departments
ALTER COLUMN department_name TYPE VARCHAR(25);

--oef4
ALTER TABLE projects
    ADD CONSTRAINT chk_project_name_upper
        CHECK (project_name = UPPER(project_name))
        NOT VALID;

UPDATE projects
SET project_name = UPPER(project_name)
WHERE project_name <> UPPER(project_name);

ALTER TABLE projects
    VALIDATE CONSTRAINT chk_project_name_upper;

--oef5
ALTER TABLE employees
ADD COLUMN email VARCHAR(20) NOT NULL DEFAULT 'unknown';

--oef6
ALTER TABLE departments
ALTER COLUMN department_name DROP NOT NULL;

--oef7
ALTER TABLE employees
DROP COLUMN email;

--oef8
ALTER TABLE projects
ALTER COLUMN project_name DROP NOT NULL ;

select * from pg_constraint where contype= 'c';

--oef9
ALTER TABLE family_members
DROP CONSTRAINT c_gender;

ALTER TABLE family_members
ADD CONSTRAINT c_gender
CHECK ( UPPER(gender) IN ('M','F'));

--oef10
ALTER TABLE departments
    ADD CONSTRAINT fk_manager_id
        FOREIGN KEY (manager_id)
            REFERENCES employees(employee_id);

--oef11
DROP TABLE tasks;
DROP TABLE projects;
DROP TABLE employees;
DROP TABLE locations;
DROP TABLE departments;


--oef12
SELECT department_id
FROM departments
ORDER BY department_id desc
FETCH FIRST 1 ROW ONLY ;

--13
ALTER TABLE employees
    ALTER COLUMN department_id TYPE INTEGER;
ALTER TABLE projects
    ALTER COLUMN department_id TYPE INTEGER;
ALTER TABLE locations
    ALTER COLUMN department_id TYPE INTEGER;
ALTER TABLE departments
    ALTER COLUMN department_id TYPE INTEGER;

ALTER TABLE departments
    ALTER COLUMN department_id
        ADD GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1);

--oef14
TRUNCATE TABLE departments RESTART IDENTITY CASCADE;


INSERT INTO departments
(department_name)
VALUES('ICT')

select *
from departments;

--oef15
INSERT INTO departments (department_id, department_name)
    OVERRIDING SYSTEM VALUE
VALUES (100, 'HR');

--oef16
ALTER TABLE departments
    ALTER COLUMN department_id
        DROP IDENTITY;

